// [ECMA Punctuator][1]
//
// [1]:https://tc39.es/ecma262/#sec-punctuators

declare_enum![
    NAME: Punctuator,
    Not = "!",
    NotEq = "!=",
    StrictNotEq = "!==",
    Hash = "#",
    Hashbang = "#!",
    Mod = "%",
    ModAssign = "%=",
    BitAnd = "&",
    BitAndAssign = "&=",
    LogicAnd = "&&",
    LogicAndAssign = "&&=",
    LParen = "(",
    RParen = ")",
    Mul = "*",
    MulAssign = "*=",
    Pow = "**",
    PowAssign = "**=",
    Add = "+",
    AddAssign = "+=",
    BitInc = "++",
    Comma = ",",
    Sub = "-",
    SubAssign = "-=",
    BitDec = "--",
    Dot = ".",
    Ellipsis = "...",
    Div = "/",
    DivAssign = "/=",
    Colon = ":",
    Semi = ";",
    Lt = "<",
    Le = "<=",
    BitSal = "<<",
    BitSalAssign = "<<=",
    Assign = "=",
    Arrow = "=>",
    Eq = "==",
    StrictEq = "===",
    Gt = ">",
    Ge = ">=",
    BitSar = ">>",
    BitSarAssign = ">>=",
    BitShr = ">>>",
    BitShrAssign = ">>>=",
    Question = "?",
    OptionalChain = "?.",
    Coalesce = "??",
    CoalesceAssign = "??=",
    At = "@",
    LBracket = "[",
    RBracket = "]",
    BitXor = "^",
    BitXorAssign = "^=",
    LBrace = "{",
    RBrace = "}",
    BitOr = "|",
    BitOrAssign = "|=",
    LogicOr = "||",
    LogicOrAssign = "||=",
    BitNot = "~",
];

// const TEMPLATE: &str = "`";
// const TEMPLATE_HEAD: &str = "${";
// const TEMPLATE_TAIL: &str = "}"; /* RBrace */
